# Generated by Django 3.1.2 on 2021-01-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderlineitem_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='user_profile',
        ),
    ]
