# Generated by Django 3.1.2 on 2021-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20210122_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dispute_comment',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='review',
            name='dispute_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Disputed', 'Disputed')], default='Pending', max_length=10),
        ),
    ]
