# Generated by Django 3.1.2 on 2021-01-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210123_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dispute_comment',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
    ]
