# Generated by Django 3.1.2 on 2020-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='framework',
        ),
        migrations.AddField(
            model_name='developer',
            name='framework',
            field=models.ManyToManyField(to='developers.Framework'),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='language',
        ),
        migrations.AddField(
            model_name='developer',
            name='language',
            field=models.ManyToManyField(to='developers.Language'),
        ),
    ]
