# Generated by Django 3.1.2 on 2020-11-09 22:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_auto_20201108_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spoken_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('nativeName', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='developer',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='facebook',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='github',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='linkedin',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='tagline',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='twitter',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='website',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='spoken_languages',
            field=models.ManyToManyField(to='developers.Spoken_Language'),
        ),
    ]
