# Generated by Django 3.1.2 on 2020-11-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_auto_20201109_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='spoken_languages',
            new_name='spoken_language',
        ),
    ]
