# Generated by Django 3.1.2 on 2020-11-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_auto_20201109_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spoken_language',
            options={'verbose_name': 'Spoken Language', 'verbose_name_plural': 'Spoken Languages'},
        ),
    ]
